### ISSUE TITLE
Schema should handle email2fas somehow

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bugzilla2fedmsg#16]
In the fedora-messaging world, message schemas are supposed to do most of the work that in the fedmsg world was done by [fedmsg_meta_fedora_infrastructure](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure) - producing various bits of meta-information about messages, like a human-readable summary of them, and a set of affected FAS usernames.

Because Bugzilla doesn't use FAS auth, the [Bugzilla fedmsg_meta processor](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/bz.py) uses a utility function from [fedmsg_meta_fedora_infrastructure.fasshim](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/fasshim.py) called `email2fas`, which takes an email address as input and returns a corresponding FAS username (of a FAS account with that email address attached to it) if it can.

fedora-messaging does not have an equivalent feature, so it is not straightforward to implement this in the fedora-messaging incarnation of bugzilla2fedmsg, and it isn't done yet. There was some discussion about how this can be done in #15 : @jeremycline [suggests](https://github.com/fedora-infra/bugzilla2fedmsg/pull/15#issuecomment-495343647) just depending on fedmsg_meta_fedora_infrastructure and using `email2fas` from it directly, (ab)using the fedora-messaging `consumer_config` to provide the necessary configuration. We decided to handle this separately and not as part of #15 , so I'm filing this issue to ensure it's tracked.

**Comment by AdamWill** [comment]
BTW, a consideration I didn't bring up in #15 : the way fedmsg_meta's `email2fas` works only really makes sense for *long-running* processes. It's no good for short-lived processes. Producing the FAS cache is slow and network-intensive, and fedmsg_meta only stores it as a global variable in the running process, it doesn't write it to disk or anything. As soon as the process ends, the cache is gone.

I don't know if a design has yet been drawn up for how exactly the fedora-messaging schema metadata bits will be used in real-life to back stuff like FMN and datagrepper, but if it doesn't involve a long-lived process, the fedmsg_meta design may not be good enough.

**Comment by abompard** [comment]
Another way of doing it would be to have `bugzilla2fedmsg` make the FASJSON call, and store the FAS username into the message dictionnary. Then, the schemas would just have to read it. And if `bugzilla2fedmsg` makes too many FASJSON requests, we could add a cache.

**Comment by brngylni** [comment]
I can give it a try if that's ok.
