### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bugzilla2fedmsg#17]
Current git is far past 0.3.1 - we are ported to fedora-messaging and Python 3 - but there has been no release tagged since then. It would be good to get a new release (ideally with [my schema PR](https://github.com/fedora-infra/bugzilla2fedmsg/pull/15) merged) so we can unretire the package and update it so eventually the production deployment can be updated.

@abompard

**Comment by abompard** [comment]
(A release has been made at that time, I forgot to close the ticket)
