### ISSUE TITLE
Change in message format coming from bugzilla

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bugzilla2fedmsg#9]
Heads up!

I saw activity in the comment thread of [this bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1079764) suggesting that they're going to change the message format coming out of bugzilla.

This service (bugzilla2fedmsg) *may* have to be patched to deal with that.  Maintainers here, please coordinate with the illustrious @jfearn on what that format might look like.

**Comment by ghost** [comment]
FYI we are switching to the format BMO use for their Push extension. I've put some pretty printed examples online at https://jfearn.fedorapeople.org/MessageExamples.txt

**Comment by ralphbean** [comment]
@jfearn do you have a rough ETA on when those new messages will show up?  That will function as a deadline for when this receiving code needs to be updated.

/cc @stickster

**Comment by ghost** [comment]
@ralphbean It will be in Bugzilla 5, best guess for that going in to production is early March, assuming all 5752 ducks line up :-/

I'll chase up the UMB folk to see if we can get the BZ5 publishing on another queue when it goes to public beta ... which only requires lining up 1112 ducks.

**Comment by puiterwijk** [comment]
Note: we should also update fedmsg-meta-fedora-infrastructure.
/cc @pypingou @jeremycline

**Comment by pypingou** [comment]
Not if the format doesn't change on the fedmsg side

**Comment by AdamWill** [comment]
So, @ralphbean kinda-sorta adapted to the new message format in https://github.com/fedora-infra/bugzilla2fedmsg/pull/10 , only...that's not really complete at all. I happened to notice some bad FMN notifications from Bugzilla today and dived head-first into a rat's nest of issues. I have a big PR coming which should make the handling of Bugzilla 5 upstream messages quite a lot better and fix several problems we ultimately see downstream in the fedmsg processor.

I also intend to send some changes for the fedmsg processor, to make it make better use of the message data so we can ultimately remove the 'backwards compatibility' bits from this end.

**Comment by AdamWill** [comment]
https://github.com/fedora-infra/bugzilla2fedmsg/pull/13 is my PR to improve on this.

**Comment by AdamWill** [comment]
I think this can probably be closed now?
